# Use 'generic' to be able to override CC/CXX for clang
language: generic

matrix:
  include:
    - compiler: gcc
    - compiler: clang
      addons:
        # Install a more recent clang than the default
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: COMPILER_NAME=clang-3.8 CXX=clang++-3.8 CC=clang-3.8
    - os: osx
      osx_image: xcode7.3
      script:
          - xcodebuild -target RetroArch -configuration Release -project pkg/apple/RetroArch.xcodeproj

script:
  - ./configure
  - make

env:
  global:
   - secure: "qc91ReC3OlzSh2gFaSH6TYzC2qIQvgA2AZff6J13eaH8xijAhuMzttZ0rMQJ0DWCIhPeUb0kIzVyaGoe4MwPALzpw1C1AznIWiZJ53HN+hWCOcS/af7YVPk6HPySnwqrS+Wv3AIIvIKFV2mxv21F/JbT/N+pArlRrp904Xj+KPo="
addons:
  apt:
    packages:
      - curl
      - pkg-config
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev
      - libsdl1.2-dev
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl-ttf2.0-dev
  coverity_scan:
    project:
      name: "RetroArch"
      description: "RetroArch is the official reference frontend for the libretro API."
    notification_email: libretro@gmail.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
